# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 20:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='VAT_number',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='number',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='togglId',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='timeentry',
            name='togglId',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
