# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 22:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='invoicing.Profile'),
            preserve_default=False,
        ),
    ]
