# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-10 15:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0005_auto_20170402_0849'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='date',
            field=models.DateField(default=datetime.date(2017, 5, 10), editable=False),
            preserve_default=False,
        ),
    ]
