# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-19 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0007_auto_20170510_2011'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportingTimeEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billable', models.BooleanField()),
                ('project_name', models.CharField(max_length=200)),
                ('project_client_name', models.CharField(max_length=200)),
                ('project_user_name', models.CharField(max_length=200)),
                ('project_rate', models.FloatField()),
                ('start', models.DateTimeField()),
                ('start_str', models.CharField(max_length=50)),
                ('start_day', models.IntegerField()),
                ('start_month', models.IntegerField()),
                ('start_year', models.IntegerField()),
                ('duration', models.FloatField()),
                ('duration_unit', models.CharField(choices=[('days', 'days'), ('hours', 'hours'), ('minutes', 'minutes')], default='hours', max_length=10)),
                ('togglId', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='invoice',
            name='number',
            field=models.IntegerField(blank=True, help_text='autofilled, only fill in yourself if you want to override the default', null=True, unique=True),
        ),
    ]
