# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-04-30 19:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0008_auto_20170719_1525'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReportingTimeEntry',
        ),
        migrations.AddField(
            model_name='invoice',
            name='delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
