# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-04-30 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0009_auto_20180430_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='rate',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
