# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-04-30 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0010_auto_20180430_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='default_invoice_description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
