# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-04-30 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0011_auto_20180430_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='vat_rate',
            field=models.DecimalField(decimal_places=2, default=0.21, max_digits=5),
            preserve_default=False,
        ),
    ]
