# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-06-15 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0014_auto_20180615_1358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='VAT_percentage',
        ),
        migrations.AddField(
            model_name='invoice',
            name='vat_rate',
            field=models.DecimalField(decimal_places=2, default=0.21, max_digits=5),
        ),
    ]
