# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-02-04 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0015_auto_20180615_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='vat_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='If the VAT% is not equal to the overall VAT rate', max_digits=7, null=True),
        ),
    ]
