# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-02-24 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0016_invoiceitem_vat_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='credit_template',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
