# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-02-24 19:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0017_project_credit_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='is_credit_invoice',
            field=models.BooleanField(default=False),
        ),
    ]
