# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-10-17 09:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0018_invoice_is_credit_invoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(blank=True, help_text='autofilled, only fill in yourself if you want to override the default', null=True, unique=True)),
                ('vat_rate', models.DecimalField(decimal_places=2, default=0.21, max_digits=5)),
                ('date', models.DateField(editable=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoicing.Project')),
            ],
        ),
    ]
