# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-12-21 10:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0020_auto_20191017_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bic_account_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
